### ISSUE TITLE
Route to trigger two-factor email or text

### ISSUE THREAD

**Issue by birarda** [jmaxxz/keymaker#4]
I'm attempting to use your extremely helpful postman collection to test out some API methods. Unfortunately it seems that two-factor now requires a code to validate token for email or phone before it can be used.

What route should I be hitting after the initial post to `/session` to trigger the verification email or text?

**Comment by jmaxxz** [comment]
see https://github.com/jmaxxz/keymaker/issues/5#issuecomment-360007335
