### ISSUE TITLE
Creating Guests with Pin

### ISSUE THREAD

**Issue by federice** [jmaxxz/keymaker#6]
Hi @jmaxxz  first of all many thanks for the great work on the august lock. 

I wonder if you could give me some insight on the api process. At the moment i'm trying to automate the guest creation with pin numbers.  However I cannot go beyond the creation of the USER  and not the guest, or even a way to associate pins to guest or users
I can see a "state" parameter but I've tried all the combinations which do not let me to add a pin. 

Thanks

**Comment by jmaxxz** [comment]
Are you just trying to set a pin through the rest api? If so you will need a bridge to actually add the pin to the lock. Please confirm you have a bridge first.

**Comment by federice** [comment]
Hi Jmaxxz thanks for the quick reply. Yes I do have a bridge

**Comment by federice** [comment]
I  want to create a guestuser and set a pin  through rest api

**Comment by jmaxxz** [comment]
@federice ok, I don't have a working keypad anymore. I will get back to you in the next 16hrs

**Comment by federice** [comment]
Hi Jmaxxz

You are very kind! Many thanks.

If you want I can give access to my setup / Keys - if you promise to do not
break it :))

__________________
*Fabio Federice*
*E*: fabio@federice.net

**Comment by jmaxxz** [comment]
Set pin of `{{UserId}}` to `12345`. Possible access types are `always`, `recurring`, `temporary`, and `onetime`. Only `always` and `onetime` seem to work with my lock. (I can't verify they will work with the keypad.)
```
PUT https://api-production.august.com/locks/{{LockId}}/users/{{UserId}}/pin
{
    "state": "load",
    "pin": "12345",
    "accessType": "always",
    "action":"intent"
}
```

Delete pin of `{{UserId}}`
```
PUT https://api-production.august.com/locks/{{LockId}}/users/{{UserId}}/pin
{
    "accessType": "always",
    "action": "intent",
    "pin": "12345",
    "state": "delete"
}
```

Generate an anonymous guest of `{{LockId}}`. A user id will be generated for the anonymous guest, you can use this id in the future to add remove the user.
```
POST https://api-production.august.com/unverifiedusers
{
    "firstName": "Tony",
    "lastName": "Stark",
    "lockID": "{{LockId}}",
}

Response:
{
    "id": "50ef3b13-b0e1-452a-9c75-a7ccc77271ba",
    "firstName": "Tony",
    "lastName": "Stark",
    "pin": "41664"
}
```

Sync pins for `{{LockId}}`
```
PUT https://api-production.august.com/locks/{{LockId}}/pins/sync
```

Get 'random' pin. In case you can't figure out how to use a good random number generator.
```
https://api-production.august.com/locks/{{LockId}}/pin
```
## Misc notes
* After calling creating a unverified user you must use the set pin api to actually add the user to the lock.
* August uses the regex /[0-9]{4,14}/ to validate pins.
* In most places in the august api {{UserId}} can be replaced with `email:example@example.com` or the equivalent phone syntax


## ❗️ IMPORTANT ❗️ 

* When changing a pin in the August app it first deletes the old pin and then adds the new one. I **strongly** recommend you do the same.
* Sync pins after making any changes to pins.

**Comment by federice** [comment]
Jmaxxz you are genius!!! I was struggling with the unverified user as well
as the "load" part.

Many many thanks

__________________
*Fabio Federice*
*E*: fabio@federice.net

**Comment by jmaxxz** [comment]
@federice can you share more about the automation you are doing? Always curious to see how this stuff gets used.

⚠️ Note I updated the delete step. You want to use **intent**, **commit** is only used to tell the api you've actually removed the pin from the lock. **intent** is always used to tell the api that you would like a pin change to occur on the lock, **commit** is triggered once the change has been carried out.

**Comment by federice** [comment]
@jmaxxz  Yes I'm working on intent and commit properly. I figured that out. 

We run AirBnBs with an August lock and a management Software called Airbnb.io. At the moment our average stay  is 2 days, which means that in an ideal week we have up to 3 different guests staying on, which is a burden to change codes for each new guest, as we have manually login to august app, create the user, copy the random pin from the august lock to a message to the guest and so on...  All of that taking care of not doing too early, too late, or in the wrong place.

For now I'm using Zapier (probably you might know a more elegant solution) to receive a trigger from Airbnb.io with guest name, phone number, check-in and check-out date, so I can send 3 triggers to August lock to create an unverified user, set pin number and finally sync. 

This will fully automate the process as the August API will tie hand with the Mgmt Software of accepting a guest, send all instructions and answer all questions captured and now finally thanks to you, it will send a predetermined password to the guests.  

If you wish, I'm more than happy to have a remote session to go through step-by-step if you are interested.

**Comment by wootwoot1234** [comment]
@federice I was wondering if you were able to get this to work, set lock codes for different users?  If so, would you be willing to share some of your code?  I'm trying to figure out how the locks syncing works, deleting pins/users, etc.  Any insight would be much appreciated.  :)
