### ISSUE TITLE
I have been trying to get this to work but am stuck on the "validate" email or phone.

### ISSUE THREAD

**Issue by jmaxxz** [jmaxxz/keymaker#7]
I have been trying to get this to work but am stuck on the "validate" email or phone.

I posted **/validation/email** and got a valid code sent to my e-mail.

I tried posting this to the following **validate/email**.
```javascript
{
"email":"email-addresss",
"code": "code-from-email"
}
```

and I am getting the following error in the body:
```javascript
{
    "userId": "user-id",
    "_value": "email:email-address",
    "resolution": "token_incomplete"
}
```

Does anyone have any idea what I'm doing wrong? I am using the x-august-access-token from the **validation/email** response header.

_Originally posted by @juancortez in https://github.com/jmaxxz/keymaker/issues/5#issuecomment-447515312_

**Comment by federice** [comment]
Hi Juan,

Yes that's right.  When you send the first POST  with Body  "value":"
email" you will receive an access token, which should be used in the header
of the reply post with Validation ( Code and email).

So your Validate/email post should have  in the header
x-august-access-token (and the token from the previous step)

**Comment by jmaxxz** [comment]
@juancortez  you need to specify your email like this

```
"email:you@example.com"
```

Just like you do `"phone:1111111111"`

**Comment by jmaxxz** [comment]
@juancortez Ignore it, if the result status code is 200 I think it worked. If the jwt token you got says you have phone and email you are golden

**Comment by jmaxxz** [comment]
I've confirmed that "token_incomplete" is not an error. It is working if you get this and status 200.

**Comment by mcohen9** [comment]
> Hi Juan, Yes that's right. When you send the first POST with Body "value":" email" you will receive an access token, which should be used in the header of the reply post with Validation ( Code and email). So your Validate/email post should have in the header x-august-access-token (and the token from the previous step)


Hey man awesome work here, not sure what im doing wrong maybe you can help me. 
I do the initial SignIn request and my response is this:

    "applicationId": "",
    "userId": "",
    "vInstallId": false,
    "vPassword": false,
    "vEmail": false,
    "vPhone": false,
    "hasInstallId": true,
    "hasPassword": true,
    "hasEmail": true,
    "hasPhone": true,
    "isLockedOut": false,
    "oauth": {},
    "homeAccess": "",
    "captcha": "",
    "email": [],
    "phone": [],
    "expiresAt": "2020-06-26T18:46:44.878Z",
    "temporaryAccountCreationPasswordLink": "",
    "iat": 1582829204,
    "exp": 1593197204,
    "FirstName": "",
    "LastName": ""

Then I use the x-august-access-token from that response to send a verification code. 
I get the email and text properly. 

You said I should have 2 tokens in the request to POST verify the email code. 
Not sure what the second token is and where it goes. 

I have the access-token from the reset email request and then i use it for then next request as the august-access-token. 

This is my response: Status 200 

    "userId": "",
    "_value": "phone: <REMOVED>",
    "resolution": "token_incomplete"

Then I use the x-august-access-token given in that response header for other request but is does not work. This is the response:

     "code": "InvalidCredentials",
    "message": "access token not associated with a user"

Hope someone can help me out.

**Comment by jmaxxz** [comment]
1. Login with username and password
This should return a response with
```
"vPassword": true,
"vEmail": false,
"vPhone": false,
```
set your ApiKey to the `x-august-access-token` in the response header

2. Send password reset token to phone
3. Verify phone
set your ApiKey to the `x-august-access-token` in the response header
4. Send password reset toke to email
set your ApiKey to the `x-august-access-token` in the response header

Now you have a token  that should work. Once you've gone through this process with an install id you can renew the token with that install id just by loggin in.

**Comment by jmaxxz** [comment]
Sure would be nice if August would just publish documentation on their apis ;-).
